recipe/meta.yaml
Rebuild using the new `llvmdev` build now that the upstream CodeView registers patch has been applied.
xref: https://github.com/conda-forge/llvmdev-feedstock/pull/44
=> Bump build number to 1

recipe/meta.yaml
Low-effort addition of clang tools extra:
https://clang.llvm.org/extra/index.html
Extra tools are built as part of clangdev and included
in the clang-tools package.  This grows the size of the
clang-tools package to ~110MB and I'm sure will make the buildtime
quite a bit longer.
fixes #10
Checklist
=> Add clang extra tools

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_clang_variantcling_v0.6.yaml, .ci_support/linux_64_clang_variantdefault.yaml, .ci_support/linux_64_clang_variantroot_20190625.yaml, .ci_support/linux_64_clang_variantroot_20191220.yaml, .ci_support/linux_64_clang_variantroot_20200518.yaml, .ci_support/osx_64_clang_variantcling_v0.6.yaml, .ci_support/osx_64_clang_variantdefault.yaml, .ci_support/osx_64_clang_variantroot_20190625.yaml, .ci_support/osx_64_clang_variantroot_20191220.yaml, .ci_support/osx_64_clang_variantroot_20200518.yaml, .ci_support/win_64_clang_variantcling_v0.6.yaml, .ci_support/win_64_clang_variantdefault.yaml, .ci_support/win_64_clang_variantroot_20190625.yaml, .ci_support/win_64_clang_variantroot_20191220.yaml, .ci_support/win_64_clang_variantroot_20200518.yaml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, LICENSE.txt, README.md, azure-pipelines.yml, recipe/build_clangdev.sh, recipe/conda_build_config.yaml, recipe/meta.yaml
The sysroot has been moved from `x86_64-conda_cos6-linux-gnu` to `x86_64-conda-linux-gnu` which causes the use of `$HOST` here to be wrong. This breaks `root` and `cling` as they need to find use the headers at runtime. I was a little surprised nobody had reported issues but it turns out the `CONDA_BUILD_SYSROOT` environment variable is normally and hides the problem for most people.
@SylvainCorlay In case you come across the error below, this should fix it (after it's merged and cling is rebuilt).
```
In file included from input_line_1:1:
In file included from /home/cburr/miniconda3/envs/test-cling/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/include/c++/7.5.0/new:39:
In file included from /home/cburr/miniconda3/envs/test-cling/bin/../lib/gcc/x86_64-conda …
```
=> Follow sysroot changes

recipe/meta.yaml, recipe/patches/disable-wundef-prefix.patch
=> Disable -Werror,-Wundef-prefix=TARGET_OS as they are not yet defined in the 10.9 SDK used for osx-64

.ci_support/linux_64_variantdefault.yaml, .scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, README.md, build-locally.py, recipe/meta.yaml, recipe/patches/0004-clang-fix-sysroot-dupe-headers-a3a243.patch
See https://github.com/llvm/llvm-project/commit/a3a24316087d0e1b4db0b8fee19cdee8b7968032 for details. This fixes c++ compilation with MacOS SDK 11.3.
Checklist
=> Add upstream patch that fixes compiling when there are dupe c++ headers.

recipe/install_clang_tools.sh, recipe/meta.yaml
Working on the stripped package mentioned #147 to allow a much lighter weight clang-format package for use in tools like pre-commit.
Not sure about quite a few things, but hopefully this is a start. I'm not sure where the files are coming from - I'd like to reuse them from the ones built in clang-tools if possible - and it seems like there are there, except the tests show `clang-format` missing when I build it locally.
=> feat: include clang-format as a stripped package

recipe/meta.yaml, recipe/patches/0001-Find-conda-gcc-installation.patch, recipe/patches/0002-Fix-sysroot-detection-for-linux.patch, recipe/patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0004-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0005-Set-VERSION-in-osx-as-well.patch, recipe/patches/0006-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0007-Only-error-on-undefined-TARGET_OS_OSX.patch, recipe/patches/0008-set-libclang-SOVERSION-unconditionally.patch
Noticed just now that the full-versioned libs had [slipped through](https://github.com/regro/libcfgraph/blob/master/artifacts/libclang13/conda-forge/linux-64/libclang13-15.0.7-default_h3e3d535_0.json#L226-L229) the versioned libclang13 effort.
FYI @isuruf
=> ensure we don't package libclang with full (so)version

.ci_support/linux_64_variantdefault.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, recipe/meta.yaml
Bot [choked](https://conda-forge.org/status/#version_updates) on something.
```
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!
Please check the URLs in your recipe with version '16.0.2' to make sure they exist!
We also found the following errors:
- could not hash URL template 'https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz'
```
=> clangdev 16.0.2

recipe/meta.yaml, recipe/patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
Checklist
This issue fixes that if the environment variable CONDA_BUILD_SYSROOT is defined, the '-sysroot' option passed as argument is ignored and even leads to an unused-command-line-argument warning for it.
This issue is especially problematic in cross-compiler scenario - like emscripten - where it is essential to be able to switch between native and cross' sysroot by the '-sysroot' option on demand.
As this issue is a long standing one, we might even want to backport it to older versions, but this is for now out of scope for this patch
=> Fix sysroot issue about CONDA_BUILD_SYSROOT

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_variantdefault.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .circleci/config.yml, .github/workflows/automerge.yml, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml, recipe/patches/0001-Find-conda-gcc-installation.patch, recipe/patches/0002-Fix-sysroot-detection-for-linux.patch, recipe/patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0004-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0005-Set-VERSION-in-osx-as-well.patch, recipe/patches/0006-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0007-Only-error-on-undefined-TARGET_OS_OSX.patch, recipe/patches/0008-set-libclang-SOVERSION-unconditionally.patch
From #216 
CC @katietz 
Needs to cherry-pick https://github.com/conda-forge/clangdev-feedstock/commit/fb1465aa8a2fa787a865d5c38ea289a2b39d616b
=> [14.x] backport sysroot fix

recipe/get_cpu_triplet.sh, recipe/install_clang_symlinks.sh, recipe/install_clangxx.sh, recipe/meta.yaml
=> Reduce deps for clang on Linux and set sysroot

recipe/meta.yaml
Jump to `_3` is intentional, as some other 19.0.0.dev0 builds are on `_2` already.
=> [dev] clangdev 19.0.0.dev0, take 3

recipe/install_clang_symlinks.sh, recipe/meta.yaml
Necessary for https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/133; partial backport from #297
=> [16.x] package `$TRIPLE-clang-cpp` symlink on linux

.ci_support/osx_64_variantdefault.yaml, .ci_support/osx_64_variantroot_63004.yaml, .ci_support/osx_arm64_variantdefault.yaml, .ci_support/osx_arm64_variantroot_63004.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
since
https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/408e182a971b21e5f784daa05078ff3c0d475646 forces a more modern libcxx on macOS, pinning here to libcxx breaks downstream packages such as cppyy, see https://github.com/conda-forge/cppyy-cling-feedstock/pull/62#issuecomment-2305187040
As indicated in
https://github.com/conda-forge/clangdev-feedstock/pull/300#issuecomment-2283805407 there should be no problem using libcxx 17 here as well.
Checklist
=> [13.x] Build with a newer libcxx on macOS

recipe/meta.yaml
For #310, using builds from https://github.com/conda-forge/libcxx-feedstock/pull/183
=> [main] switch to using libcxx-devel

.ci_support/osx_64_variantdefault.yaml, .ci_support/osx_64_variantroot_63202.yaml, .ci_support/osx_arm64_variantdefault.yaml, .ci_support/osx_arm64_variantroot_63202.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> [16.x] add missing pin to libcxx-devel; fix libcxx run-export

recipe/meta.yaml
Oversight in #311, see [here](https://github.com/conda-forge/clangdev-feedstock/pull/311/files#r1737118145)
=> add missing pin to libcxx-devel; fix libcxx run-export

recipe/meta.yaml
\+ forward-ports of #311 and #315
=> clangdev v19.1.0.rc4

recipe/meta.yaml
=> [17.x] add missing pin to libcxx-devel; fix libcxx run-export

recipe/meta.yaml
CI for the newly-created branch at 811977470f2c38120da8d6e353b1c3d64d691e88 failed in the presence of `libcxx 19`.
Give the solver a hand in figuring out how to resolve the environment.
=> [18.x] fix build w.r.t. libcxx-devel pins

recipe/meta.yaml
Descoped from #362, ran into
```
In file included from mytest.cxx:1:
In file included from %PREFIX%\Library\lib\gcc\x86_64-w64-mingw32\15.1.0\include\c++\iostream:43:
In file included from %PREFIX%\Library\lib\gcc\x86_64-w64-mingw32\15.1.0\include\c++\ostream:42:
In file included from %PREFIX%\Library\lib\gcc\x86_64-w64-mingw32\15.1.0\include\c++\bits/ostream.h:43:
In file included from %PREFIX%\Library\lib\gcc\x86_64-w64-mingw32\15.1.0\include\c++\ios:42:
In file included from %PREFIX%\Library\lib\gcc\x86_64-w64-mingw32\15.1.0\include\c++\iosfwd:44:
In file included from %PREFIX%\Library\lib\gcc\x86_64-w64-mingw32\15.1.0\include\c++\bits/postypes.h:42:
%PREFIX%\Library\lib\gcc\x86_64-w64-mingw32\15.1.0\include\c++\cwchar:49:10: fatal error: 'wchar.h' file not found
49 | #include …
```
=> Re-enable mingw C++ test

recipe/meta.yaml, recipe/patches/0011-Reapply-CUDA-HIP-Add-a-__device__-version-of-std-__g.patch
Fix https://github.com/conda-forge/clangdev-feedstock/issues/384, pending check with @xhochy .
Checklist
=> Update cuda_wrappers/bits/c++config.h to latest version

.ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, README.md, recipe/install_clang.bat, recipe/install_clang.sh, recipe/install_clangxx.bat, recipe/install_clangxx.sh, recipe/meta.yaml
Backport https://github.com/conda-forge/clangdev-feedstock/pull/387
=> [19.x] Move clang++-<maj> to clang-<maj> package
