conda-forge/clangdev-feedstock

recipe/bld.bat, recipe/meta.yaml
This depends on https://github.com/conda-forge/llvmdev-feedstock/pull/11.
=> Switch to vs 2015

recipe/meta.yaml
Companion PR to https://github.com/conda-forge/llvmdev-feedstock/pull/15
=> Cling feature

.appveyor.yml, .azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .azure-pipelines/build_steps.sh, .azure-pipelines/run_docker_build.sh, .circleci/build_steps.sh, .circleci/run_osx_build.sh, README.md, azure-pipelines.yml, recipe/build_clangdev.sh, recipe/meta.yaml, recipe/root-patches/0001-add-raii-to-buffer-delayed-infos.patch, recipe/root-patches/0002-constify-nfc.patch, recipe/root-patches/0003-default-template-arg-hack.patch, recipe/root-patches/0004-refactor-generation-counter.patch, recipe/root-patches/0005-refactor-in-RequireCompleteDeclContext.patch
Checklist
As mentioned by @SylvainCorlay in https://github.com/conda-forge/staged-recipes/pull/7414 it is desirable to avoid vendering `clangdev` when building [`ROOT`](https://root.cern/) for conda-forge. To do this additional patches are needed in `clangdev` which are included in this PR.
=> Add patches required for building ROOT

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, recipe/Improve-logic-for-finding-the-macos-sysroot-for-cond.patch, recipe/meta.yaml
Fixes a typo in #46, see https://github.com/conda-forge/cling-feedstock/issues/23 for details.
cc @SylvainCorlay
=> Fix macOS sysroot

recipe/meta.yaml, recipe/patches/0001-Find-conda-gcc-installation.patch, recipe/patches/0002-Fix-sysroot-detection-for-linux.patch
=> Fixes for ppc64le and aarch64

recipe/bld.bat, recipe/build.sh, recipe/install_clang.bat, recipe/install_clang.sh, recipe/install_clang_tools.bat, recipe/install_clang_tools.sh, recipe/install_clangdev.bat, recipe/install_clangdev.sh, recipe/install_clangxx.bat, recipe/install_clangxx.sh, recipe/install_libclang.bat, recipe/install_libclang.sh, recipe/meta.yaml, recipe/patches/0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0003-clang-Fix-normalizeProgramName-s-handling-of-dots-ou.patch
This should be backward compatible with previous builds.
=> Split packages

recipe/meta.yaml
=> Remove run_constrains for libclang

recipe/install_clang_tools.bat, recipe/meta.yaml
=> Remove libclang.dll from clang-tools

recipe/build.sh, recipe/install_clang.sh, recipe/install_clang_tools.sh, recipe/install_clangdev.sh, recipe/install_libclang.sh, recipe/meta.yaml, recipe/osx_hack.sh
=> Update to 8.0.1

recipe/build.sh, recipe/install_clang.sh, recipe/install_clang_tools.sh, recipe/install_clangdev.sh, recipe/install_libclang.sh, recipe/meta.yaml, recipe/osx_hack.sh
=> Use bootstrap compiler and fix libLTO

recipe/meta.yaml, recipe/patches/amd-roc-2.7.0.diff
=> Add ROCM patches

recipe/meta.yaml, recipe/mytest.cxx
Checklist
Closes #74 .
The test is expected to fail until PR https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/9 is merged and used by clangdev. Until then, this PR is labelled as WIP.
=> Add clang++ compilation test

.appveyor.yml, .azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .azure-pipelines/run_docker_build.sh, .ci_support/linux_clang_variantcling_v0.6.yaml, .ci_support/linux_clang_variantroot_v6.18.02.yaml, .ci_support/osx_clang_variantcling_v0.6.yaml, .ci_support/osx_clang_variantroot_v6.18.02.yaml, .ci_support/win_clang_variantcling_v0.6cxx_compilervs2015.yaml, .ci_support/win_clang_variantroot_v6.18.02cxx_compilervs2015.yaml, .circleci/config.yml, .gitattributes, README.md, recipe/build_clangdev.bat, recipe/build_clangdev.sh, recipe/conda_build_config.yaml, recipe/meta.yaml
=> New version of the cling patches

README.md, recipe/meta.yaml
Depends on https://github.com/conda-forge/llvmdev-feedstock/pull/81
Checklist
@conda-forge-admin, please rerender
=> Update to 9.0.1

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_clang_variantroot_20191220.yaml, .ci_support/osx_clang_variantcling_v0.6.yaml, .ci_support/osx_clang_variantdefault.yaml, .ci_support/osx_clang_variantroot_20191220.yaml, .ci_support/win_clang_variantcling_v0.6cxx_compilervs2015vc14.yaml, .ci_support/win_clang_variantdefaultcxx_compilervs2015vc14.yaml, .ci_support/win_clang_variantroot_20191220cxx_compilervs2015vc14.yaml, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Update 5.x variant for ROOT 6.20 patches

recipe/meta.yaml
Checklist
I have not contributed/do not plan to contribute to this feedstock.
@conda-forge-admin, please rerender
=> Remove mattwala from maintainers

recipe/meta.yaml
=> Fix clang run_constrained

recipe/install_libclang.sh, recipe/install_libclang_cpp.sh, recipe/meta.yaml
=> libclang-cpp

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_clang_variantcling_v0.7.yaml, .ci_support/osx_64_clang_variantcling_v0.7.yaml, .ci_support/win_64_clang_variantcling_v0.7.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, recipe/conda_build_config.yaml
=> Package cling 0.7 variant

recipe/build.sh, recipe/install_clang.bat, recipe/install_clang.sh, recipe/install_clang_symlinks.bat, recipe/install_clang_symlinks.sh, recipe/install_clangxx.bat, recipe/install_clangxx.sh, recipe/meta.yaml
=> split clang-MAJOR

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_clang_variantcling_v0.8.yaml, .ci_support/linux_64_clang_variantdefault.yaml, .ci_support/linux_64_clang_variantroot_20201127.yaml, .ci_support/linux_aarch64_clang_variantcling_v0.8.yaml, .ci_support/linux_aarch64_clang_variantdefault.yaml, .ci_support/linux_aarch64_clang_variantroot_20201127.yaml, .ci_support/osx_64_clang_variantcling_v0.8.yaml, .ci_support/osx_arm64_clang_variantcling_v0.8.yaml, .ci_support/osx_arm64_clang_variantdefault.yaml, .ci_support/osx_arm64_clang_variantroot_20201127.yaml, .ci_support/win_64_clang_variantcling_v0.8.yaml, .scripts/run_docker_build.sh, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Build cling v0.8 variant

recipe/meta.yaml
=> Remove cling 0.8 workaround

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/win_64_.yaml, recipe/meta.yaml
Fixing https://github.com/conda-forge/scipy-feedstock/pull/169/commits/d94e69a9bd87a15d0d708a0bc22afdc2be72dde3 (though not 100% sure I got this right @isuruf)
=> add zlib as a run-dependency on windows

conda-forge.yml, recipe/install_clang_tools.sh, recipe/meta.yaml
Checklist
Fixes #48
Fixes #147
=> Fix deps for clang-tools and add version symlinks

recipe/install_libclang.sh, recipe/meta.yaml
=> fix libclang output

recipe/install_clang_format.bat, recipe/install_clang_format.sh, recipe/install_clang_tools.sh, recipe/meta.yaml
=> Fix clang-format

recipe/conda_build_config.yaml, recipe/meta.yaml
=> Use LLVM variant

recipe/meta.yaml, recipe/patches/0008-set-libclang-SOVERSION-unconditionally.patch
Plus #199 
Waiting for builds from https://github.com/conda-forge/llvmdev-feedstock/pull/197
=> bump to 16.0.0.rc2

recipe/bld.bat
10'000s of lines of useless output help no-one.
=> silence robocopy

.azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_variantdefault.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml, recipe/patches/0001-Find-conda-gcc-installation.patch, recipe/patches/0002-Fix-sysroot-detection-for-linux.patch, recipe/patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0004-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0005-Set-VERSION-in-osx-as-well.patch, recipe/patches/0006-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0007-Only-error-on-undefined-TARGET_OS_OSX.patch, recipe/patches/0008-set-libclang-SOVERSION-unconditionally.patch
=> [15.x] backport sysroot fix

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_variantdefault.yaml, .ci_support/linux_64_variantroot_62804.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_aarch64_variantroot_62804.yaml, .ci_support/linux_ppc64le_variantroot_62804.yaml, .ci_support/osx_64_variantroot_62804.yaml, .ci_support/osx_arm64_variantroot_62804.yaml, .scripts/run_osx_build.sh, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml, recipe/patches/root/0001-Deserialize-LValuePathSerializationHelper-s-type-pro.patch, recipe/patches/root/0002-Do-not-evaluate-value-dependent-immediate-invocation.patch, recipe/patches/root/0003-Backport-clang-Allocate-2-bits-to-store-the-constexp.patch, recipe/patches/root/0004-Implement-a-module-attribute-optional-to-allow-missi.patch, recipe/patches/root/0005-Add-cplusplus20-as-module-requirement.patch, recipe/patches/root/0006-survive-Inon-accessible-directory.patch
=>  Update ROOT patches for 6.28.4 

recipe/meta.yaml
=> [13.x] Fix build string for clang output

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, recipe/get_cpu_triplet.sh, recipe/install_clang_symlinks.sh, recipe/install_clangxx.sh, recipe/meta.yaml
Forward-port #251
Closes #249
Closes #246
Closes #239 (while we're at it...)
=> [main] Reduce deps for clang on Linux and set sysroot

.ci_support/linux_64_variantdefault.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, recipe/meta.yaml
=> [16.x] Add root variant to track_features

recipe/meta.yaml, recipe/patches/0009-Find-ROCm-device-library-in-conda-layout.patch
=> Find ROCm device library in conda layout

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_variantdefault.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, azure-pipelines.yml, build-locally.py, recipe/build.sh, recipe/meta.yaml, recipe/patches/0001-Fix-sysroot-detection-for-linux.patch, recipe/patches/0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0003-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0004-Set-VERSION-in-osx-as-well.patch, recipe/patches/0005-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0006-Only-error-on-undefined-TARGET_OS_OSX.patch, recipe/patches/0007-set-libclang-SOVERSION-unconditionally.patch, recipe/patches/0008-Make-PIE-default-on-macOS-too.patch, recipe/patches/0009-Find-ROCm-device-library-in-conda-layout.patch, recipe/patches/0010-Find-conda-gcc-installation.patch
=> [17.x] reinstate patch for gcc toolchain detection

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, azure-pipelines.yml, build-locally.py, recipe/meta.yaml, recipe/patches/0001-Fix-sysroot-detection-for-linux.patch, recipe/patches/0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0003-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0004-Set-VERSION-in-osx-as-well.patch, recipe/patches/0005-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0006-Only-error-on-undefined-TARGET_OS_OSX.patch, recipe/patches/0007-set-libclang-SOVERSION-unconditionally.patch, recipe/patches/0008-Make-PIE-default-on-macOS-too.patch, recipe/patches/0009-Find-conda-gcc-installation.patch
=> [16.x] reinstate patch for gcc toolchain detection

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_variantdefault.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, azure-pipelines.yml, build-locally.py, recipe/meta.yaml, recipe/patches/0001-Fix-sysroot-detection-for-linux.patch, recipe/patches/0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0003-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0004-Set-VERSION-in-osx-as-well.patch, recipe/patches/0005-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0006-Only-error-on-undefined-TARGET_OS_OSX.patch, recipe/patches/0007-set-libclang-SOVERSION-unconditionally.patch, recipe/patches/0008-Find-conda-gcc-installation.patch
=> [15.x] reinstate patch for gcc toolchain detection

recipe/meta.yaml
=> clangdev 18.1.4

.azure-pipelines/azure-pipelines-osx.yml, recipe/meta.yaml
=> clangdev 18.1.5

recipe/meta.yaml
Also switch to github sources due to bot issues, see https://github.com/regro/cf-scripts/issues/2531 for details
=> clangdev v18.1.7

.ci_support/linux_64_variantdefault.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .ci_support/win_64_.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml, recipe/patches/0001-Find-conda-gcc-installation.patch, recipe/patches/0002-Fix-sysroot-detection-for-linux.patch, recipe/patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0004-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0005-Set-VERSION-in-osx-as-well.patch, recipe/patches/0006-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0007-set-libclang-SOVERSION-unconditionally.patch, recipe/patches/0008-Make-PIE-default-on-macOS-too.patch, recipe/patches/0009-Find-ROCm-device-library-in-conda-layout.patch
Match `dev` branch with llvmdev feedstock; build a consistent stack from LLVM main, in order to test newer flang.
=> [dev] clangdev 19.0.0.dev0

.ci_support/linux_64_.yaml, .scripts/build_steps.sh, recipe/install_clang_symlinks.sh, recipe/meta.yaml, recipe/patches/0001-Find-conda-gcc-installation.patch, recipe/patches/0002-Fix-sysroot-detection-for-linux.patch, recipe/patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch, recipe/patches/0004-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch, recipe/patches/0005-Set-VERSION-in-osx-as-well.patch, recipe/patches/0006-Fix-crosscompiling-LLVM-tools.patch, recipe/patches/0007-set-libclang-SOVERSION-unconditionally.patch, recipe/patches/0008-Make-PIE-default-on-macOS-too.patch, recipe/patches/0009-Find-ROCm-device-library-in-conda-layout.patch
Necessary for https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/133
=> package `$TRIPLE-clang-cpp` symlink on linux

recipe/meta.yaml
=> Allow different clang versions to exist in the same env

recipe/meta.yaml, recipe/patches/0010-Add-conda-mingw-paths.patch
=> support mingw on windows

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, build-locally.py, recipe/build.sh, recipe/meta.yaml
Build off of https://github.com/llvm/llvm-project/commit/0cda970ecc8a885acf7298a61370a1368b0ea39b
=> [dev] update build from main for testing flang-rt

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_variantroot_63406.yaml, .ci_support/linux_aarch64_variantroot_63406.yaml, .ci_support/linux_ppc64le_variantroot_63406.yaml, .ci_support/osx_64_variantroot_63406.yaml, .ci_support/osx_arm64_variantroot_63406.yaml, .gitignore, .scripts/run_docker_build.sh, README.md, build-locally.py, recipe/conda_build_config.yaml, recipe/meta.yaml, recipe/patches/root/0029-UPSTREAM-clang-repl-Fix-printing-preprocessed-tokens.patch, recipe/patches/root/0030-cxxmodules-Don-t-complain-when-modulemap-for-implici.patch
Checklist
For now this is WIP, I am testing locally that these changes also result in a valid build of the `root-feedstock`
=> [18.x] Patches for ROOT 6.34.06

recipe/install_clangxx.bat, recipe/install_clangxx.sh, recipe/meta.yaml
For context, see https://github.com/conda-forge/jaxlib-feedstock/pull/313#issuecomment-2888401509
Checklist
=> Add a symlink for clangxx-MAJOR

recipe/install_clangxx.bat, recipe/install_clangxx.sh, recipe/meta.yaml
=> [19.x] Add a symlink for clangxx-MAJOR

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_variantcling_1.2.yaml, .ci_support/linux_64_variantdefault.yaml, .ci_support/linux_64_variantroot_63604.yaml, .ci_support/linux_aarch64_variantcling_1.2.yaml, .ci_support/linux_aarch64_variantdefault.yaml, .ci_support/linux_aarch64_variantroot_63604.yaml, .ci_support/linux_ppc64le_variantcling_1.2.yaml, .ci_support/linux_ppc64le_variantdefault.yaml, .ci_support/linux_ppc64le_variantroot_63604.yaml, .ci_support/migrations/libxml2214.yaml, .ci_support/osx_64_variantcling_1.2.yaml, .ci_support/osx_64_variantdefault.yaml, .ci_support/osx_64_variantroot_63604.yaml, .ci_support/osx_arm64_variantcling_1.2.yaml, .ci_support/osx_arm64_variantdefault.yaml, .ci_support/osx_arm64_variantroot_63604.yaml, .ci_support/win_64_variantcling_1.2.yaml, .ci_support/win_64_variantdefault.yaml, conda-forge.yml, recipe/meta.yaml
Will need this for root etc. to participate in the 2.14 migration
=> [18.x] Rebuild for libxml2 2.14

recipe/install_clang.bat, recipe/install_clang.sh, recipe/install_clangxx.bat, recipe/install_clangxx.sh, recipe/meta.yaml
This makes it possible to have multiple clang++ executables in same environment.
=> Move clang++-21 to clang-21 package

.ci_support/linux_64_.yaml, .ci_support/linux_aarch64_.yaml, .ci_support/linux_ppc64le_.yaml, README.md, recipe/install_clang.bat, recipe/install_clang.sh, recipe/install_clangxx.bat, recipe/install_clangxx.sh, recipe/meta.yaml
=> [20.x] Move clang++-<maj> to clang-<maj> package
